<?php
/** @var string $schema_array_export */
?>
/**
 * This file is autogenerated, do not edit!
 * The source of truth is always the relational database, edit its schema directly and run 'radaptor build:db' again.
 *
 * @phpstan-type ShapeSQLColumn array{
 *     column_name: string,
 *     type_sql: string,
 *     type_php: string,
 *     comment: string,
 *     default: ?string,
 *     extra: string,
 *     is_optional: bool,
 *     is_processable: bool,
 *     is_primary_key: bool,
 *     is_auto_increment: bool
 * }
 * @phpstan-type ShapeSQLTable array{
 *     table_name: string,
 *     fields: list<ShapeSQLColumn>,
 *     field_names: list<string>,
 *     pkeys: list<string>,
 *     processable_fields: array<string, string>,
 *     is_auto_increment: bool
 * }
 */
class DbSchemaData
{
	/** @var array<string, array<string, ShapeSQLTable>> */
	public const array TABLE_DATA = <?= $schema_array_export ?>;

	/** @var array<int, array<string, array<string, ShapeSQLTable>>> */
	private static array $_runtime_schema_stack = [];

	private static int $_runtime_schema_counter = 0;

	/**
	 * @param array<string, array<string, ShapeSQLTable>> $schema_info
	 */
	public static function pushRuntimeSchema(array $schema_info): int
	{
		$token = ++self::$_runtime_schema_counter;
		self::$_runtime_schema_stack[$token] = $schema_info;

		return $token;
	}

	public static function popRuntimeSchema(int $token): void
	{
		unset(self::$_runtime_schema_stack[$token]);
	}

	/**
	 * @template T
	 * @param array<string, array<string, ShapeSQLTable>> $schema_info
	 * @param callable(): T $callback
	 * @return T
	 */
	public static function withRuntimeSchema(array $schema_info, callable $callback): mixed
	{
		$token = self::pushRuntimeSchema($schema_info);

		try {
			return $callback();
		} finally {
			self::popRuntimeSchema($token);
		}
	}

	/**
	 * @param string $table_name
	 * @param string $dsn
	 * @return ShapeSQLTable|null
	 */
	public static function getTableData(string $table_name, string $dsn = ''): ?array
	{
		$clean_dsn = self::normalizeCleanDsn($dsn);

		foreach (array_reverse(self::$_runtime_schema_stack, true) as $schema_info) {
			if (isset($schema_info[$clean_dsn][$table_name])) {
				return $schema_info[$clean_dsn][$table_name];
			}
		}

		return self::TABLE_DATA[$clean_dsn][$table_name] ?? null;
	}

	/**
	 * @param string $dsn
	 * @return array<string, ShapeSQLTable>|null
	 */
	public static function getSchemaInfo(string $dsn = ''): ?array
	{
		$clean_dsn = self::normalizeCleanDsn($dsn);

		foreach (array_reverse(self::$_runtime_schema_stack, true) as $schema_info) {
			if (isset($schema_info[$clean_dsn])) {
				return $schema_info[$clean_dsn];
			}
		}

		return self::TABLE_DATA[$clean_dsn] ?? null;
	}

	private static function normalizeCleanDsn(string $dsn = ''): string
	{
		$dsn = Db::normalizeDsn($dsn);

		return Db::redactDSNUserAndPassword($dsn);
	}
}
