<?php
/**
 * @var array<string, string> $extension_map Extension => Renderer class mapping
 * @var array<int, string> $extension_order Extensions in priority order (highest first)
 */
?>
/**
 * Template renderer registry.
 *
 * Maps file extensions to renderer classes. Extensions are listed in priority order
 * for correct matching (e.g., '.blade.php' before '.php').
 *
 * @generated by CLIEventBuildTemplateRenderers - DO NOT EDIT
 */
class TemplateRenderers
{
	/**
	 * Extension to renderer class mapping.
	 * @var array<string, class-string<iTemplateRenderer>>
	 */
	protected static array $_extensionMap = <?= GeneratorHelper::formatArrayForExport($extension_map) ?>;

	/**
	 * Extensions in priority order (highest first).
	 * @var array<int, string>
	 */
	protected static array $_extensionOrder = <?= GeneratorHelper::formatArrayForExport($extension_order) ?>;

	/**
	 * Get renderer class for a file path based on extension.
	 *
	 * @param string $filePath Path to the template file
	 * @return class-string<iTemplateRenderer> Renderer class name
	 */
	public static function getRendererForPath(string $filePath): string
	{
		// Check extensions in priority order (longest/highest priority first)
		foreach (self::$_extensionOrder as $extension) {
			if (str_ends_with($filePath, $extension)) {
				return self::$_extensionMap[$extension];
			}
		}

		// Default to PHP renderer
		return 'TemplateRendererPhp';
	}

	/**
	 * Get all registered extensions in priority order.
	 *
	 * @return array<int, string>
	 */
	public static function getExtensions(): array
	{
		return self::$_extensionOrder;
	}

	/**
	 * Get the full extension-to-renderer mapping.
	 *
	 * @return array<string, class-string<iTemplateRenderer>>
	 */
	public static function getExtensionMap(): array
	{
		return self::$_extensionMap;
	}
}
