<?php
/** @var string $schema_array_export */
?>
/**
 * This file is autogenerated, do not edit!
 * The source of truth is always the relational database, edit its schema directly and run 'radaptor build:db' again.
 *
 * @phpstan-type ShapeSQLColumn array{
 *     column_name: string,
 *     type_sql: string,
 *     type_php: string,
 *     comment: string,
 *     default: ?string,
 *     extra: string,
 *     is_optional: bool,
 *     is_processable: bool,
 *     is_primary_key: bool,
 *     is_auto_increment: bool
 * }
 * @phpstan-type ShapeSQLTable array{
 *     table_name: string,
 *     fields: list<ShapeSQLColumn>,
 *     field_names: list<string>,
 *     pkeys: list<string>,
 *     processable_fields: array<string, string>,
 *     is_auto_increment: bool
 * }
 */
class DbSchemaData
{
	/** @var array<string, array<string, ShapeSQLTable>> */
	public const array TABLE_DATA = <?= $schema_array_export ?>;

	/**
	 * @param string $table_name
	 * @param string $dsn
	 * @return ShapeSQLTable|null
	 */
	public static function getTableData(string $table_name, string $dsn = ''): ?array
	{
		$dsn = Db::normalizeDsn($dsn);
		$clean_dsn = Db::redactDSNUserAndPassword($dsn);

		return self::TABLE_DATA[$clean_dsn][$table_name] ?? null;
	}

	/**
	 * @param string $dsn
	 * @return array<string, ShapeSQLTable>|null
	 */
	public static function getSchemaInfo(string $dsn = ''): ?array
	{
		$dsn = Db::normalizeDsn($dsn);
		$clean_dsn = Db::redactDSNUserAndPassword($dsn);

		return self::TABLE_DATA[$clean_dsn] ?? null;
	}
}
