<?php
assert(isset($entity_class_name) && is_string($entity_class_name));
assert(isset($table_info) && $table_info instanceof structSQLTable);

// Generate the type alias name (e.g., EntityUser -> ShapeEntityUser)
$type_name = 'Shape' . $entity_class_name;
?>
/**
 * @phpstan-type <?= $type_name ?> array{
<?php foreach ($table_info->fields as $field) {
	$shape_type = $field->type_php === 'bool' ? 'bool|int' : $field->type_php;
	$shape_type .= $field->is_nullable ? '|null' : '';
	$optional_marker = $field->is_optional ? '?' : '';
	?>
 *     <?= $field->column_name ?><?= $optional_marker ?>: <?= $shape_type ?>,
<?php } ?>
 * }
 *
<?php foreach ($table_info->fields as $field) {
	// @property is always nullable because __get returns null for missing keys
	$property_type = $field->type_php === 'bool' ? 'bool|int|null' : ('?' . $field->type_php);
	$extra_comment = !empty($field->extra) ? ' (' . $field->extra . ')' : '';
	$bool_comment = $field->type_php === 'bool' ? ' DB returns 0/1, use loose comparison (==)' : '';
	?>
 * @property <?= $property_type ?> $<?= $field->column_name ?><?= $extra_comment ?><?= $bool_comment ?><?= "\n"; ?>
<?php } ?>
 *
 * @extends SQLEntity<<?= $type_name ?>>
 */
class <?= $entity_class_name ?> extends SQLEntity
{
	public const string TABLE_NAME = '<?= $table_info->table_name ?>';

	// ============================================================================
	// Autogenerated method override for IDE autocomplete and type safety
	// ============================================================================

	/**
	 * {@inheritDoc}
	 * @param <?= $type_name ?> $data
	 */
	public function __construct(array $data)
	{
		parent::__construct($data);
	}

	/**
	 * {@inheritDoc}
	 * @param <?= $type_name ?> $data
	 */
	public function patch(array $data): static
	{
		return parent::patch($data);
	}

	/**
	 * {@inheritDoc}
	 * @param <?= $type_name ?> $data
	 */
	public static function saveFromArray(array $data): static
	{
		return parent::saveFromArray($data);
	}

	/**
	 * {@inheritDoc}
	 * @param <?= $type_name ?> $data
	 */
	public static function createFromArray(array $data): static
	{
		return parent::createFromArray($data);
	}

	/**
	 * {@inheritDoc}
	 * @param int|array<string, mixed> $id
	 * @param <?= $type_name ?> $data
	 */
	public static function updateById(int|array $id, array $data): static
	{
		return parent::updateById($id, $data);
	}

	/**
	 * {@inheritDoc}
	 * @param <?= $type_name ?> $data
	 */
	public static function instantiateFromArray(array $data): static
	{
		return parent::instantiateFromArray($data);
	}
}
