<?php

class CLICommandBuildAutoloader extends AbstractCLICommand
{
	public function getName(): string
	{
		return 'Build autoloader';
	}

	public function getDocs(): string
	{
		return <<<'DOC'
			Regenerate the class autoloader registry.

			Usage: radaptor build:autoloader

			Scans the codebase for class files and generates the autoload map.
			DOC;
	}

	public function isWebRunnable(): bool
	{
		return true;
	}
	public function getRiskLevel(): string
	{
		return 'build';
	}

	public function run(): void
	{
		self::create();
	}

	public static function create(): void
	{
		AutoloaderFailsafe::reset();
		$classIndex = array_map(
			fn (string $filePath) => PackagePathHelper::toStoragePath($filePath),
			AutoloaderFailsafe::getAutoloadMap()
		);

		// Manually adding autogenerated files, as they were not being created yet
		$classIndex['AutoloadGenerated'] = ApplicationConfig::GENERATED_AUTOLOADER_FILE;
		$classIndex['LayoutTypes'] = ApplicationConfig::GENERATED_LAYOUTS_FILE;
		$classIndex['TemplateList'] = ApplicationConfig::GENERATED_TEMPLATES_FILE;
		$classIndex['TestTemplateList'] = ApplicationConfig::GENERATED_TEST_TEMPLATES_FILE;
		$classIndex['WidgetList'] = ApplicationConfig::GENERATED_WIDGETS_FILE;
		$classIndex['ThemeList'] = ApplicationConfig::GENERATED_THEME_DATA_FILE;
		$classIndex['FormList'] = ApplicationConfig::GENERATED_FORMS_FILE;
		$classIndex['PluginList'] = ApplicationConfig::GENERATED_PLUGINS_FILE;
		$classIndex['ImportExportDatasetList'] = ApplicationConfig::GENERATED_IMPORT_EXPORT_DATASETS_FILE;
		$classIndex['RoleList'] = ApplicationConfig::GENERATED_ROLES_FILE;

		ksort($classIndex);

		$class_index_export = GeneratorHelper::formatArrayForExport($classIndex);

		$cache_content = GeneratorHelper::fetchTemplate(
			'build_autoloader',
			[
				'class_index_export' => $class_index_export,
			]
		);

		if (($cacheFilename_handle = fopen(DEPLOY_ROOT . ApplicationConfig::GENERATED_AUTOLOADER_FILE, "w"))) {
			$success = fwrite($cacheFilename_handle, str_replace("	", "	", $cache_content));

			if ($success !== false) {
				echo "<b>autoloader</b> leíró fájl sikeresen létrehozva!\n";
			} else {
				echo "Hiba történt az <b>autoloader</b> leíró fájl írásakor!\n";
			}
		} else {
			echo "<span style=\"background-color:red;\">Ismeretlen hiba az autoloader leíró készítése közben!</span>\n";
		}
	}
}
