<?php

/**
 * @phpstan-type ShapeEntityUserconfig array{
 *     rowid?: int,
 *     user_id: int,
 *     config_key: string,
 *     value: string,
 * }
 *
 * @property ?int $rowid (auto_increment)
 * @property ?int $user_id
 * @property ?string $config_key
 * @property ?string $value
 *
 * @extends SQLEntity<ShapeEntityUserconfig>
 */
class EntityUserconfig extends SQLEntity
{
	public const string TABLE_NAME = 'userconfig';

	// ============================================================================
	// Autogenerated method override for IDE autocomplete and type safety
	// ============================================================================

	/**
	 * {@inheritDoc}
	 * @param ShapeEntityUserconfig $data
	 */
	public function __construct(array $data)
	{
		parent::__construct($data);
	}

	/**
	 * {@inheritDoc}
	 * @param ShapeEntityUserconfig $data
	 */
	public function patch(array $data): static
	{
		return parent::patch($data);
	}

	/**
	 * {@inheritDoc}
	 * @param ShapeEntityUserconfig $data
	 */
	public static function saveFromArray(array $data): static
	{
		return parent::saveFromArray($data);
	}

	/**
	 * {@inheritDoc}
	 * @param ShapeEntityUserconfig $data
	 */
	public static function createFromArray(array $data): static
	{
		return parent::createFromArray($data);
	}

	/**
	 * {@inheritDoc}
	 * @param int|array<string, mixed> $id
	 * @param ShapeEntityUserconfig $data
	 */
	public static function updateById(int|array $id, array $data): static
	{
		return parent::updateById($id, $data);
	}

	/**
	 * {@inheritDoc}
	 * @param ShapeEntityUserconfig $data
	 */
	public static function instantiateFromArray(array $data): static
	{
		return parent::instantiateFromArray($data);
	}
}
