<?php

/**
 * @phpstan-type ShapeEntityUser array{
 *     user_id?: int,
 *     username?: string,
 *     is_active?: bool|int,
 *     last_seen?: string,
 *     timezone?: string|null,
 *     locale?: string,
 *     password?: string,
 * }
 *
 * @property ?int $user_id (auto_increment)
 * @property ?string $username
 * @property bool|int|null $is_active DB returns 0/1, use loose comparison (==)
 * @property ?string $last_seen
 * @property ?string $timezone
 * @property ?string $locale
 * @property ?string $password
 *
 * @extends SQLEntity<ShapeEntityUser>
 */
class EntityUser extends SQLEntity
{
	public const string TABLE_NAME = 'users';

	// ============================================================================
	// Autogenerated method override for IDE autocomplete and type safety
	// ============================================================================

	/**
	 * {@inheritDoc}
	 * @param ShapeEntityUser $data
	 */
	public function __construct(array $data)
	{
		parent::__construct($data);
	}

	/**
	 * {@inheritDoc}
	 * @param ShapeEntityUser $data
	 */
	public function patch(array $data): static
	{
		return parent::patch($data);
	}

	/**
	 * {@inheritDoc}
	 * @param ShapeEntityUser $data
	 */
	public static function saveFromArray(array $data): static
	{
		return parent::saveFromArray($data);
	}

	/**
	 * {@inheritDoc}
	 * @param ShapeEntityUser $data
	 */
	public static function createFromArray(array $data): static
	{
		return parent::createFromArray($data);
	}

	/**
	 * {@inheritDoc}
	 * @param int|array<string, mixed> $id
	 * @param ShapeEntityUser $data
	 */
	public static function updateById(int|array $id, array $data): static
	{
		return parent::updateById($id, $data);
	}

	/**
	 * {@inheritDoc}
	 * @param ShapeEntityUser $data
	 */
	public static function instantiateFromArray(array $data): static
	{
		return parent::instantiateFromArray($data);
	}
}
