<?php

/**
 * Mapping table for user-to-usergroup assignments.
 * Composite primary key: (user_id, usergroup_id).
 *
 * @phpstan-type ShapeEntityUsersUsergroupsMapping array{
 *     user_id: int,
 *     usergroup_id: int,
 * }
 *
 * @property int $user_id (composite PK)
 * @property int $usergroup_id (composite PK)
 *
 * @extends SQLEntity<ShapeEntityUsersUsergroupsMapping>
 * @phpstan-consistent-constructor
 */
class EntityUsersUsergroupsMapping extends SQLEntity
{
	public const string TABLE_NAME = 'users_usergroups_mapping';

	// ============================================================================
	// Autogenerated method override for IDE autocomplete and type safety
	// ============================================================================

	/**
	 * {@inheritDoc}
	 * @param ShapeEntityUsersUsergroupsMapping $data
	 */
	public function __construct(array $data)
	{
		parent::__construct($data);
	}

	/**
	 * {@inheritDoc}
	 * @param ShapeEntityUsersUsergroupsMapping $data
	 */
	public function patch(array $data): static
	{
		return parent::patch($data);
	}

	/**
	 * Override _doSave for composite PK mapping table.
	 * Uses insertOrUpdateHelper for idempotent upsert behavior.
	 *
	 * @param ShapeEntityUsersUsergroupsMapping $data
	 * @return static
	 * @throws EntitySaveException on insert failure
	 */
	protected static function _doSave(array $data, ?int $id = null): static
	{
		$table = static::getTableName();
		$result = DbHelper::insertOrUpdateHelper(table: $table, savedata: $data);

		if ($result === null) {
			throw new EntitySaveException(
				'Failed to insert record into ' . $table,
				static::class,
				$data
			);
		}

		return new static($data);
	}

	/**
	 * {@inheritDoc}
	 * @param ShapeEntityUsersUsergroupsMapping $data
	 */
	public static function saveFromArray(array $data): static
	{
		return parent::saveFromArray($data);
	}

	/**
	 * {@inheritDoc}
	 * @param ShapeEntityUsersUsergroupsMapping $data
	 */
	public static function createFromArray(array $data): static
	{
		return parent::createFromArray($data);
	}

	/**
	 * {@inheritDoc}
	 * @param ShapeEntityUsersUsergroupsMapping $data
	 */
	public static function instantiateFromArray(array $data): static
	{
		return parent::instantiateFromArray($data);
	}

	// ============================================================================
	// Custom query methods
	// ============================================================================

	/**
	 * Find all usergroup mappings for a user.
	 *
	 * @param int $userId
	 * @return array<static>
	 */
	public static function findByUserId(int $userId): array
	{
		return static::findMany(['user_id' => $userId]);
	}

	/**
	 * Find all user mappings for a usergroup.
	 *
	 * @param int $usergroupId
	 * @return array<static>
	 */
	public static function findByUsergroupId(int $usergroupId): array
	{
		return static::findMany(['usergroup_id' => $usergroupId]);
	}

	/**
	 * Check if a user-usergroup assignment exists.
	 *
	 * @param int $userId
	 * @param int $usergroupId
	 * @return bool
	 */
	public static function exists(int $userId, int $usergroupId): bool
	{
		return static::findFirst(['user_id' => $userId, 'usergroup_id' => $usergroupId]) !== null;
	}

	/**
	 * Delete a user-usergroup mapping by composite key.
	 *
	 * @param int $userId
	 * @param int $usergroupId
	 * @return bool
	 */
	public static function deleteByKey(int $userId, int $usergroupId): bool
	{
		return static::delete(['user_id' => $userId, 'usergroup_id' => $usergroupId]);
	}
}
