<?php

/**
 * Mapping table for user-to-role assignments.
 * Composite primary key: (user_id, role_id).
 *
 * @phpstan-type ShapeEntityUsersRolesMapping array{
 *     user_id: int,
 *     role_id: int,
 * }
 *
 * @property int $user_id (composite PK)
 * @property int $role_id (composite PK)
 *
 * @extends SQLEntity<ShapeEntityUsersRolesMapping>
 * @phpstan-consistent-constructor
 */
class EntityUsersRolesMapping extends SQLEntity
{
	public const string TABLE_NAME = 'users_roles_mapping';

	// ============================================================================
	// Autogenerated method override for IDE autocomplete and type safety
	// ============================================================================

	/**
	 * {@inheritDoc}
	 * @param ShapeEntityUsersRolesMapping $data
	 */
	public function __construct(array $data)
	{
		parent::__construct($data);
	}

	/**
	 * {@inheritDoc}
	 * @param ShapeEntityUsersRolesMapping $data
	 */
	public function patch(array $data): static
	{
		return parent::patch($data);
	}

	/**
	 * Override _doSave for composite PK mapping table.
	 * Uses insertOrUpdateHelper for idempotent upsert behavior.
	 *
	 * @param ShapeEntityUsersRolesMapping $data
	 * @return static
	 * @throws EntitySaveException on insert failure
	 */
	protected static function _doSave(array $data, ?int $id = null): static
	{
		$table = static::getTableName();
		$result = DbHelper::insertOrUpdateHelper(table: $table, savedata: $data);

		if ($result === null) {
			throw new EntitySaveException(
				'Failed to insert record into ' . $table,
				static::class,
				$data
			);
		}

		return new static($data);
	}

	/**
	 * {@inheritDoc}
	 * @param ShapeEntityUsersRolesMapping $data
	 */
	public static function saveFromArray(array $data): static
	{
		return parent::saveFromArray($data);
	}

	/**
	 * {@inheritDoc}
	 * @param ShapeEntityUsersRolesMapping $data
	 */
	public static function createFromArray(array $data): static
	{
		return parent::createFromArray($data);
	}

	/**
	 * {@inheritDoc}
	 * @param ShapeEntityUsersRolesMapping $data
	 */
	public static function instantiateFromArray(array $data): static
	{
		return parent::instantiateFromArray($data);
	}

	// ============================================================================
	// Custom query methods
	// ============================================================================

	/**
	 * Find all role mappings for a user.
	 *
	 * @param int $userId
	 * @return array<static>
	 */
	public static function findByUserId(int $userId): array
	{
		return static::findMany(['user_id' => $userId]);
	}

	/**
	 * Find all user mappings for a role.
	 *
	 * @param int $roleId
	 * @return array<static>
	 */
	public static function findByRoleId(int $roleId): array
	{
		return static::findMany(['role_id' => $roleId]);
	}

	/**
	 * Check if a user-role assignment exists.
	 *
	 * @param int $userId
	 * @param int $roleId
	 * @return bool
	 */
	public static function exists(int $userId, int $roleId): bool
	{
		return static::findFirst(['user_id' => $userId, 'role_id' => $roleId]) !== null;
	}

	/**
	 * Get roles with details (title, role name) for a user.
	 * Returns array of role data with role_id, role, title.
	 *
	 * @param int $userId
	 * @return array<array{role_id: int, role: string, title: string}>
	 */
	public static function getRolesWithDetailsForUser(int $userId): array
	{
		$query = "
			SELECT r.node_id AS role_id, r.role, r.title
			FROM users_roles_mapping urm
			JOIN roles_tree r ON r.node_id = urm.role_id
			WHERE urm.user_id = ?
			ORDER BY r.title
		";

		return DbHelper::prexecute($query, [$userId])?->fetchAll(PDO::FETCH_ASSOC) ?? [];
	}

	/**
	 * Delete a user-role mapping by composite key.
	 *
	 * @param int $userId
	 * @param int $roleId
	 * @return bool
	 */
	public static function deleteByKey(int $userId, int $roleId): bool
	{
		return static::delete(['user_id' => $userId, 'role_id' => $roleId]);
	}
}
