<?php

/**
 * Mapping table for usergroup-to-role assignments.
 * Composite primary key: (usergroup_id, role_id).
 *
 * @phpstan-type ShapeEntityUsergroupsRolesMapping array{
 *     usergroup_id: int,
 *     role_id: int,
 * }
 *
 * @property int $usergroup_id (composite PK)
 * @property int $role_id (composite PK)
 *
 * @extends SQLEntity<ShapeEntityUsergroupsRolesMapping>
 * @phpstan-consistent-constructor
 */
class EntityUsergroupsRolesMapping extends SQLEntity
{
	public const string TABLE_NAME = 'usergroups_roles_mapping';

	// ============================================================================
	// Autogenerated method override for IDE autocomplete and type safety
	// ============================================================================

	/**
	 * {@inheritDoc}
	 * @param ShapeEntityUsergroupsRolesMapping $data
	 */
	public function __construct(array $data)
	{
		parent::__construct($data);
	}

	/**
	 * {@inheritDoc}
	 * @param ShapeEntityUsergroupsRolesMapping $data
	 */
	public function patch(array $data): static
	{
		return parent::patch($data);
	}

	/**
	 * Override _doSave for composite PK mapping table.
	 * Uses insertOrUpdateHelper for idempotent upsert behavior.
	 *
	 * @param ShapeEntityUsergroupsRolesMapping $data
	 * @return static
	 * @throws EntitySaveException on insert failure
	 */
	protected static function _doSave(array $data, ?int $id = null): static
	{
		$table = static::getTableName();
		$result = DbHelper::insertOrUpdateHelper(table: $table, savedata: $data);

		if ($result === null) {
			throw new EntitySaveException(
				'Failed to insert record into ' . $table,
				static::class,
				$data
			);
		}

		return new static($data);
	}

	/**
	 * {@inheritDoc}
	 * @param ShapeEntityUsergroupsRolesMapping $data
	 */
	public static function saveFromArray(array $data): static
	{
		return parent::saveFromArray($data);
	}

	/**
	 * {@inheritDoc}
	 * @param ShapeEntityUsergroupsRolesMapping $data
	 */
	public static function createFromArray(array $data): static
	{
		return parent::createFromArray($data);
	}

	/**
	 * {@inheritDoc}
	 * @param ShapeEntityUsergroupsRolesMapping $data
	 */
	public static function instantiateFromArray(array $data): static
	{
		return parent::instantiateFromArray($data);
	}

	// ============================================================================
	// Custom query methods
	// ============================================================================

	/**
	 * Find all role mappings for a usergroup.
	 *
	 * @param int $usergroupId
	 * @return array<static>
	 */
	public static function findByUsergroupId(int $usergroupId): array
	{
		return static::findMany(['usergroup_id' => $usergroupId]);
	}

	/**
	 * Find all usergroup mappings for a role.
	 *
	 * @param int $roleId
	 * @return array<static>
	 */
	public static function findByRoleId(int $roleId): array
	{
		return static::findMany(['role_id' => $roleId]);
	}

	/**
	 * Check if a usergroup-role assignment exists.
	 *
	 * @param int $usergroupId
	 * @param int $roleId
	 * @return bool
	 */
	public static function exists(int $usergroupId, int $roleId): bool
	{
		return static::findFirst(['usergroup_id' => $usergroupId, 'role_id' => $roleId]) !== null;
	}

	/**
	 * Get roles with details (title, role name) for a usergroup.
	 * Returns array of role data with role_id, role, title.
	 *
	 * @param int $usergroupId
	 * @return array<array{role_id: int, role: string, title: string}>
	 */
	public static function getRolesWithDetailsForUsergroup(int $usergroupId): array
	{
		$query = "
			SELECT r.node_id AS role_id, r.role, r.title
			FROM usergroups_roles_mapping ugr
			JOIN roles_tree r ON r.node_id = ugr.role_id
			WHERE ugr.usergroup_id = ?
			ORDER BY r.title
		";

		return DbHelper::prexecute($query, [$usergroupId])?->fetchAll(PDO::FETCH_ASSOC) ?? [];
	}

	/**
	 * Get assigned roles for multiple usergroups in a single query.
	 *
	 * @param array<int> $usergroupIds
	 * @return array<int, array<array{role_id: int, role: string, title: string}>>
	 */
	public static function getRolesForMultipleUsergroups(array $usergroupIds): array
	{
		if (empty($usergroupIds)) {
			return [];
		}

		$placeholders = implode(',', array_fill(0, count($usergroupIds), '?'));

		$query = "
			SELECT
				ugr.usergroup_id,
				r.node_id AS role_id,
				r.role,
				r.title
			FROM usergroups_roles_mapping ugr
			JOIN roles_tree r ON r.node_id = ugr.role_id
			WHERE ugr.usergroup_id IN ({$placeholders})
			ORDER BY r.title
		";

		$rows = DbHelper::prexecute($query, $usergroupIds)?->fetchAll(PDO::FETCH_ASSOC) ?? [];

		$result = [];

		foreach ($rows as $row) {
			$usergroupId = (int) $row['usergroup_id'];

			if (!isset($result[$usergroupId])) {
				$result[$usergroupId] = [];
			}

			$result[$usergroupId][] = [
				'role_id' => (int) $row['role_id'],
				'role' => $row['role'],
				'title' => $row['title'],
			];
		}

		return $result;
	}

	/**
	 * Delete a usergroup-role mapping by composite key.
	 *
	 * @param int $usergroupId
	 * @param int $roleId
	 * @return bool
	 */
	public static function deleteByKey(int $usergroupId, int $roleId): bool
	{
		return static::delete(['usergroup_id' => $usergroupId, 'role_id' => $roleId]);
	}
}
