<?php

/**
 * The autogenerated Roles class will extend this class.
 */
class Roles extends RoleList
{
	/**
	 * Retrieve the role tree for a given parent ID.
	 *
	 * @param int $parent_id The ID of the parent node.
	 * @return array<int, array{
	 *     node_id: int,
	 *     parent_id: int,
	 *     title: string,
	 *     role: string,
	 *     lft: int,
	 *     rgt: int
	 * }>
	 */
	public static function getRoleTree(int $parent_id): array
	{
		return NestedSet::getChildren('roles_tree', $parent_id, [
			'title',
			'role',
		]);
	}

	/**
	 * Retrieves the values of a role from the roles_tree table.
	 *
	 * @param int $role_id The ID of the role to retrieve.
	 * @return array{
	 *     node_id: int,
	 *     lft: int,
	 *     rgt: int,
	 *     parent_id: int,
	 *     title: string,
	 *     description: string,
	 *     role: string
	 * }|null The values of the role, or null if the role does not exist.
	 */
	public static function getRoleValues(int $role_id): ?array
	{
		return DbHelper::selectOne('roles_tree', ['node_id' => $role_id]);
	}

	/**
	 * Adds a new role to the roles_tree table.
	 *
	 * @param array $savedata An associative array containing the data to save for the new role.
	 * @param int $parent_id The ID of the parent role, or 0 if this is a top-level role.
	 * @return int|null The ID of the newly created role, or null if the operation failed.
	 */
	public static function addRole(array $savedata, int $parent_id = 0): ?int
	{
		return NestedSet::addNode('roles_tree', $parent_id, $savedata);
	}

	/**
	 * Updates an existing role in the roles_tree table.
	 *
	 * @param array $savedata An associative array containing the updated data for the role.
	 * @param int $id The ID of the role to update.
	 * @return int The number of rows affected by the update operation.
	 */
	public static function updateRole(array $savedata, int $id): int
	{
		return DbHelper::updateHelper('roles_tree', $savedata, $id);
	}

	/**
	 * Moves a role to a new position in the roles_tree table.
	 *
	 * @param int $id The ID of the role to move.
	 * @param int $parent_id The ID of the new parent role, or 0 if this is a top-level role.
	 * @param int $position The new position of the role relative to its siblings.
	 * @return bool True if the move was successful, false otherwise.
	 */
	public static function moveToPosition(int $id, int $parent_id, int $position): bool
	{
		return NestedSet::moveToPosition('roles_tree', $id, $parent_id, $position);
	}

	/**
	 * Recursively deletes a role and all of its child roles from the roles_tree table.
	 *
	 * @param int $role_id The ID of the role to delete.
	 * @return array{success: bool, erroneous: int, role: int} An associative array with the following keys:
	 *   - 'success': bool - True if the deletion was successful, false otherwise.
	 *   - 'erroneous': int - The number of roles that failed to be deleted.
	 *   - 'role': int - The number of roles that were successfully deleted.
	 */
	public static function deleteRoleRecursive(int $role_id): array
	{
		$role_count = 0;
		$erroneous_count = 0;

		$data = Roles::getRoleValues($role_id);

		$lft = $data['lft'];
		$rgt = $data['rgt'];

		if ($rgt - $lft == 1) {
			if (Roles::deleteRole($role_id)) {
				++$role_count;
			} else {
				++$erroneous_count;
			}
		} else {
			$stmt = Db::instance()
					  ->prepare("SELECT node_id, (rgt-lft) AS rgtlft FROM roles_tree WHERE lft >= ? AND rgt <= ? ORDER BY rgtlft ASC, node_id DESC");
			$stmt->execute([
				$lft,
				$rgt,
			]);

			$rs = $stmt->fetchAll(PDO::FETCH_ASSOC);

			foreach ($rs as $node) {
				++$role_count;
				Roles::deleteRole($node['node_id']);
			}
		}

		if ($erroneous_count + $role_count > 0) {
			$success = true;
		} else {
			$success = false;
		}

		return ([
			'success' => $success,
			'erroneous' => $erroneous_count,
			'role' => $role_count,
		]);
	}

	/**
	 * Deletes a role from the roles_tree table.
	 *
	 * @param int $node_id The ID of the role to be deleted.
	 * @return bool True if the role was successfully deleted, false otherwise.
	 */
	public static function deleteRole(int $node_id): bool
	{
		return NestedSet::deleteNode('roles_tree', $node_id);
	}

	/**
	 * Assigns a role to a user.
	 *
	 * @param int $role_id The ID of the role to assign.
	 * @param int $user_id The ID of the user to assign the role to.
	 * @return bool True if the role was successfully assigned, false otherwise.
	 */
	public static function assignToUser(int $role_id, int $user_id): bool
	{
		try {
			EntityUsersRolesMapping::saveFromArray([
				'role_id' => $role_id,
				'user_id' => $user_id,
			]);

			return true;
		} catch (EntitySaveException) {
			return false;
		}
	}

	/**
	 * Assigns a role to a user group.
	 *
	 * @param int $role_id The ID of the role to assign.
	 * @param int $usergroup_id The ID of the user group to assign the role to.
	 * @return bool True if the role was successfully assigned, false otherwise.
	 */
	public static function assignToUsergroup(int $role_id, int $usergroup_id): bool
	{
		try {
			EntityUsergroupsRolesMapping::saveFromArray([
				'role_id' => $role_id,
				'usergroup_id' => $usergroup_id,
			]);

			return true;
		} catch (EntitySaveException) {
			return false;
		}
	}

	/**
	 * Removes a role assignment from a user.
	 *
	 * @param int $role_id The ID of the role to remove.
	 * @param int $user_id The ID of the user to remove the role from.
	 * @return bool True if the role assignment was successfully removed, false otherwise.
	 */
	public static function removeFromUser(int $role_id, int $user_id): bool
	{
		return EntityUsersRolesMapping::deleteByKey($user_id, $role_id);
	}

	/**
	 * Removes a role assignment from a user group.
	 *
	 * @param int $role_id The ID of the role to remove.
	 * @param int $usergroup_id The ID of the user group to remove the role from.
	 * @return bool True if the role assignment was successfully removed, false otherwise.
	 */
	public static function removeFromUsergroup(int $role_id, int $usergroup_id): bool
	{
		return EntityUsergroupsRolesMapping::deleteByKey($usergroup_id, $role_id);
	}

	/**
	 * Checks if a user is assigned a specific role.
	 *
	 * @param int $role_id The ID of the role to check.
	 * @param int $user_id The ID of the user to check.
	 * @return bool True if the user is assigned the role, false otherwise.
	 */
	public static function checkUserIsAssigned(int $role_id, int $user_id): bool
	{
		return EntityUsersRolesMapping::exists($user_id, $role_id);
	}

	/**
	 * Checks if a user group is assigned a specific role.
	 *
	 * @param int $role_id The ID of the role to check.
	 * @param int $usergroup_id The ID of the user group to check.
	 * @return bool True if the user group is assigned the role, false otherwise.
	 */
	public static function checkUsergroupIsAssigned(int $role_id, int $usergroup_id): bool
	{
		return EntityUsergroupsRolesMapping::exists($usergroup_id, $role_id);
	}

	/**
	 * Checks if the current user has the specified role.
	 *
	 * @param string $role The role to check.
	 * @return bool True if the current user has the specified role, false otherwise.
	 */
	public static function hasRole(string $role): bool
	{
		$current_user_id = User::getCurrentUserId();

		// TODO: Double-check if we are using roles with system users, but no user should mean no role in general
		if ($current_user_id < 0) {
			return false;
		}

		return self::userHasRole($current_user_id, $role);
	}

	public static function userHasRole(int $user_id, string $role): bool
	{
		if ($user_id <= 0) {
			return false;
		}

		return self::evaluateUserHasRole($user_id, $role);
	}

	private static function evaluateUserHasRole(int $user_id, string $role): bool
	{
		$cacheKey = Cache::key([
			'user_id' => $user_id,
			'role' => $role,
		]);
		$cached = Cache::get(self::class, $cacheKey);

		if (!is_null($cached)) {
			return (bool) $cached;
		}

		$role_data = DbHelper::selectOne('roles_tree', ['role' => $role], '', 'lft, rgt');

		if (is_null($role_data)) {
			return Cache::set(self::class, $cacheKey, false);
		}

		$query = "
            SELECT
                rt.node_id
            FROM
                roles_tree rt
            WHERE rt.lft <= ?
                AND rt.rgt >= ?
            ORDER BY rt.lft;
        ";

		$roles = DbHelper::prexecute(
			$query,
			[$role_data['lft'], $role_data['rgt']]
		)?->fetchAll(PDO::FETCH_COLUMN);

		if (is_null($roles) || empty($roles)) {
			return Cache::set(self::class, $cacheKey, false);
		}

		$imploded_role_ids = implode(',', $roles);

		$user_query = "
            SELECT
                COUNT(1) AS user_has_role
            FROM
                users_roles_mapping
            WHERE user_id = ?
                AND role_id IN ({$imploded_role_ids});
        ";

		$user_has_role = DbHelper::selectOneColumnFromQuery(
			$user_query,
			[$user_id]
		);

		if ($user_has_role) {
			return Cache::set(self::class, $cacheKey, true);
		}

		$usergroup_query = "
        SELECT
            COUNT(1) AS usergroup_has_role
        FROM
            usergroups_roles_mapping
        WHERE usergroup_id IN
            (SELECT
                usergroup_id
            FROM
                users_usergroups_mapping
            WHERE user_id = ?)
            AND role_id IN ({$imploded_role_ids}) ;
        ";

		$usergroup_has_role = DbHelper::selectOneColumnFromQuery(
			$usergroup_query,
			[$user_id]
		);

		if ($usergroup_has_role) {
			return Cache::set(self::class, $cacheKey, true);
		}

		return Cache::set(self::class, $cacheKey, false);
	}

	public static function roleNameExists(string $role): bool
	{
		if (defined(RoleList::class . '::ROLE_' . strtoupper($role))) {
			return true;
		}

		return false;
	}
}
